import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import Calendar from "./components/Calendar";
import MonthlySummary from "./components/MonthlySummary";
import TransactionMenu from "./components/TransactionMenu";
import TransactionForm from "./components/TransactionForm";
import { useState } from "react";
import { Transaction } from "@/type";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [currentMonth, setCurrentMonth] = useState(new Date());

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ display: "flex" }}>
          <Box sx={{ flexGrow: 1 }}>
            <MonthlySummary
              transactions={transactions}
              setTransactions={setTransactions}
              currentMonth={currentMonth}
            />
            <Calendar
              transactions={transactions}
              currentMonth={currentMonth}
              setCurrentMonth={setCurrentMonth}
            />
          </Box>
          <Box sx={{ flexGrow: 1 }}>
            <TransactionMenu />
            <TransactionForm />
          </Box>
        </Box>
      </main>
    </>
  );
}
