import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import Calendar from "./components/Calendar";
import MonthlySummary from "./components/MonthlySummary";
import TransactionMenu from "./components/TransactionMenu";
import TransactionForm from "./components/TransactionForm";
import { useState } from "react";
import { Transaction } from "@/type";
import { format } from "date-fns";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [currentMonth, setCurrentMonth] = useState(new Date());

  const today = format(new Date(), "yyyy-MM-dd");
  const [currentDay, setCurrentDay] = useState(today);

  const [isModalOpen, setIsModalOpen] = useState(false);

  const closeModal = () => {
    setIsModalOpen(!isModalOpen);
  };

  const handleAddTransactionForm = () => {
    setIsModalOpen(!isModalOpen);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ display: "flex" }}>
          <Box sx={{ flexGrow: 1 }}>
            <MonthlySummary
              transactions={transactions}
              setTransactions={setTransactions}
              currentMonth={currentMonth}
            />
            <Calendar
              today={today}
              transactions={transactions}
              currentMonth={currentMonth}
              setCurrentMonth={setCurrentMonth}
              currentDay={currentDay}
              setCurrentDay={setCurrentDay}
            />
          </Box>
          <Box sx={{ flexGrow: 1 }}>
            <TransactionMenu
              transactions={transactions}
              currentMonth={currentMonth}
              currentDay={currentDay}
              handleAddTransactionForm={handleAddTransactionForm}
            />
            <TransactionForm
              closeModal={closeModal}
              isModalOpen={isModalOpen}
            />
          </Box>
        </Box>
      </main>
    </>
  );
}
